server:
  port: 0

spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888
  webflux:
    base-path: /api/v1

kafka:
  topics:
    customerCreated: product-created
  groups:
    customerService: product-service-group