server:
  port: 0  # Permite que el puerto se asigne automáticamente

spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://config-server:8888  # ✅ <--- CAMBIO CLAVE: antes decía localhost
  webflux:
    base-path: /api/v1

kafka:
  topics:
    customerCreated: customer-created
  groups:
    customerService: customer-service-group
